version: '3.7'
services:
    consumer_app:
        build:
            context: .
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - core-network
networks:
    core-network:
            driver: bridge
