export const types = {
  //Toasts
  SET_TOAST: "SET_TOAST",
  REMOVE_TOAST: "REMOVE_TOAST",

  //THeme
  SET_THEME: "SET_THEME",

  //User Authentication
  USER_LOADED: "USER_LOADED",
  AUTH_ERROR: "AUTH_ERROR",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGOUT: "LOGOUT",
  SUCCESS_SEND_OTP: "SUCCESS_SEND_OTP",
  FAIL_SEND_OTP: "FAIL_SEND_OTP",
  SET_ORIGIN_URL: "SET_ORIGIN_URL",

  //User Profile
  GET_USER_PROFILE: "GET_USER_PROFILE",
  USER_PROFILE_ERROR: "USER_PROFILE_ERROR",
  CLEAR_USER_PROFILE: "CLEAR_USER_PROFILE",
  ACCOUNT_DELETED: "ACCOUNT_DELETED",
  GET_CURRENT_USER_PROFILE_ONLINE_WALLET_INFO: "GET_CURRENT_USER_PROFILE_ONLINE_WALLET_INFO",
  GET_CURRENT_USER_PROFILE_ONLINE_WALLET_INFO_SUCCESS:
    "GET_CURRENT_USER_PROFILE_ONLINE_WALLET_INFO_SUCCESS",
  GET_CURRENT_USER_PROFILE_ONLINE_WALLET_INFO_FAIL:
    "GET_CURRENT_USER_PROFILE_ONLINE_WALLET_INFO_FAIL",
  SUCCESS_PAY_FOR_ONLINE_WALLET: "SUCCESS_PAY_FOR_ONLINE_WALLET",
  SUCCESS_PAY_FOR_ONLINE_WALLET_SUCCESS: "SUCCESS_PAY_FOR_ONLINE_WALLET_SUCCESS",
  SUCCESS_PAY_FOR_ONLINE_WALLET_FAIL: "SUCCESS_PAY_FOR_ONLINE_WALLET_FAIL",
  UPDATE_ONLINE_WALLET_ASSETS: "UPDATE_ONLINE_WALLET_ASSETS",
  REFUND_ORDER_COST_TO_ONLINE_WALLET: "REFUND_ORDER_COST_TO_ONLINE_WALLET",
  
  //Hamburger Menu
  SET_HAMBURGERMENU: "SET_HAMBURGERMENU",
  REMOVE_HAMBURGERMENU: "REMOVE_HAMBURGERMENU",

  //VenuesGroup
  GET_VENUES_GROUP: "GET_VENUES_GROUP",
  CLEAR_VENUES_GROUP: "CLEAR_VENUES_GROUP",
  VENUES_GROUP_ERROR: "VENUES_GROUP_ERROR",

  //Venues
  GET_VENUE: "GET_VENUE",
  VENUE_ERROR: "VENUE_ERROR",
  CLEAR_VENUE: "CLEAR_VENUE",
  HANDLE_VENUE_STATUS_SOCKET: "HANDLE_VENUE_STATUS_SOCKET",

  //Venue Order Settings
  GET_ORDER_SETTINGS: "GET_ORDER_SETTINGS",
  ORDER_SETTINGS_ERROR: "ORDER_SETTINGS_ERROR",
  CLEAR_VENUE_ORDER_SETTINGS: "CLEAR_VENUE_ORDER_SETTINGS",

  //Venue External Links
  GET_EXTERNAL_LINKS: "GET_EXTERNAL_LINKS",
  EXTERNAL_LINKS_ERROR: "EXTERNAL_LINKS_ERROR",
  CLEAR_VENUE_EXTERNAL_LINKS: "CLEAR_VENUE_EXTERNAL_LINKS",

  //Venue settings
  GET_VENUE_SETTINGS: "GET_VENUE_SETTINGS",
  GET_VENUE_SETTINGS_SUCCESS: "GET_VENUE_SETTINGS_SUCCESS",
  GET_VENUE_SETTINGS_FAIL: "GET_VENUE_SETTINGS_FAIL",

  //Categories
  GET_CATEGORIES: "GET_CATEGORIES",
  CATEGORY_ERROR: "CATEGORY_ERROR",

  //Subcategories
  GET_SUBCATEGORIES: "GET_SUBCATEGORIES",
  SUBCATEGORY_ERROR: "SUBCATEGORY_ERROR",

  //Item
  SET_ITEM: "SET_ITEM",
  SET_PAGE_Y_OFFSET: "SET_PAGE_Y_OFFSET",
  ITEM_ERROR: "ITEM_ERROR",
  CLEAR_ITEM: "CLEAR_ITEM",

  //Cart
  FILTER_CURRENT_VENUE_CART_ITEMS: "FILTER_CURRENT_VENUE_CART_ITEMS",
  ADD_ITEM_TO_CART: "ADD_ITEM_TO_CART",
  DELETE_ITEM_FROM_CART: "DELETE_ITEM_FROM_CART",
  CART_ERROR: "CART_ERROR",
  PLUS_COUNT_ITEM: "PLUS_COUNT_ITEM",
  MINUS_COUNT_ITEM: "MINUS_COUNT_ITEM",
  REMOVE_ALL_ITEMS_FROM_CART: "REMOVE_ALL_ITEMS_FROM_CART",

  //Menu
  GET_MENU: "GET_MENU",
  CLEAR_MENU: "CLEAR_MENU",
  MENU_ERROR: "MENU_ERROR",

  //OrderType
  SET_ORDERTYPE: "SET_ORDERTYPE",
  ORDERTYPE_ERROR: "ORDERTYPE_ERROR",

  //OrdersHistory
  CREATE_NEW_ORDER_BY_CUSTOMER: "CREATE_NEW_ORDER_BY_CUSTOMER",
  CREATE_NEW_ORDER_BY_CUSTOMER_SUCCESS: "CREATE_NEW_ORDER_BY_CUSTOMER_SUCCESS",
  ACCEPT_NEW_ORDER_BY_MERCHANT: "ACCEPT_NEW_ORDER_BY_MERCHANT",
  READY_FOR_PICKUP_BY_MERCHANT: "READY_FOR_PICKUP_BY_MERCHANT",
  FINISH_OPEN_ORDER_BY_MERCHANT: "FINISH_OPEN_ORDER_BY_MERCHANT",
  SEND_BY_COURIER_BY_MERCHANT: "SEND_BY_COURIER_BY_MERCHANT",
  GET_ORDERS_HISTORY: "GET_ORDERS_HISTORY",
  GET_ORDERS_HISTORY_SUCCESS: "GET_ORDERS_HISTORY_SUCCESS",
  ORDERS_HISTORY_ERROR: "ORDERS_HISTORT_ERROR",
  CLEAR_ORDERS_HISTORY: "CLEAR_ORDERS_HISTORY",
  SET_SELECT_ORDER: "SET_SELECT_ORDER",
  CLEAR_SELECT_ORDER: "CLEAR_SELECT_ORDER",
  CLEAR_NEW_ORDER: "CLEAR_NEW_ORDER",
  CONNECT_TO_ONLINE_PAY: "CONNECT_TO_ONLINE_PAY",
  CONNECT_TO_ONLINE_PAY_FAIL: "CONNECT_TO_ONLINE_PAY_FAIL",
  CONNECT_TO_ONLINE_PAY_SUCCESS: "CONNECT_TO_ONLINE_PAY_SUCCESS",
  CLEAR_ONLINEPORTAL_RESPONSE:"CLEAR_ONLINEPORTAL_RESPONSE",
  SUCCESS_PAY_ORDER: "SUCCESS_PAY_ORDER",
  SUCCESS_PAY_ORDER_SUCCESS: "SUCCESS_PAY_ORDER_SUCCESS",
  GET_ORDER_BY_ID: "GET_ORDER_BY_ID",
  GET_ORDER_BY_ID_SUCCESS: "GET_ORDER_BY_ID_SUCCESS",
  ORDER_BY_ID_ERROR: "ORDER_BY_ID_ERROR",
  CLEAR_ERROR: "CLEAR_ERROR",
  CLOSE_ORDER_NOTIFIVATION_MODAL: "CLOSE_ORDER_NOTIFIVATION_MODAL",
  SET_ONLINE_PAY_METHOD: "SET_ONLINE_PAY_METHOD",
  SET_SCROLL_Y_ORDERS_HISTORY: "SET_SCROLL_Y_ORDERS_HISTORY",
  SET_SHOW_QR_CODE_MODAL: "SET_SHOW_QR_CODE_MODAL",
  GET_NEW_ORDER_BY_ID: "GET_NEW_ORDER_BY_ID",
  GET_NEW_ORDER_BY_ID_FAIL: "GET_NEW_ORDER_BY_ID_FAIL",
  GET_NEW_ORDER_BY_ID_SUCCESS: "GET_NEW_ORDER_BY_ID_SUCCESS",
  SET_PREVENT_BACK_TO_SUCCESSFUL_ORDER_PAGE:
    "SET_PREVENT_BACK_TO_SUCCESSFUL_ORDER_PAGE",
  SET_ORDER_DETAILS_SOURCE_URL: "SET_ORDER_DETAILS_SOURCE_URL",
  VALIDATION_DISCOUNT_CODE: "VALIDATION_DISCOUNT_CODE",
  VALIDATION_DISCOUNT_CODE_SUCCESS: "VALIDATION_DISCOUNT_CODE_SUCCESS",
  VALIDATION_DISCOUNT_CODE_FAIL: "VALIDATION_DISCOUNT_CODE_FAIL",
  REMOVE_DISCOUNT_CODE: "REMOVE_DISCOUNT_CODE",
  SET_DISISCOUNT_CODE: "SET_DISISCOUNT_CODE",
  UPDATE_ORDER_STATUS: "UPDATE_ORDER_STATUS",

  //ADDRESSES
  GET_USER_ADDRESSES_FOR_CONSUMER_FAIL: "GET_USER_ADDRESSES_FOR_CONSUMER_FAIL",
  GET_USER_ADDRESSES_FOR_CONSUMER: "GET_USER_ADDRESSES_FOR_CONSUMER",
  GET_USER_ADDRESSES_FOR_CONSUMER_SUCCESS:
    "GET_USER_ADDRESSES_FOR_CONSUMER_SUCCESS",

  ADD_NEW_ADDRESS_BY_CUSTOMER: "ADD_NEW_ADDRESS_BY_CUSTOMER",
  ADD_NEW_ADDRESS_BY_CUSTOMER_FAIL: "ADD_NEW_ADDRESS_BY_CUSTOMER_FAIL",
  ADD_NEW_ADDRESS_BY_CUSTOMER_SUCCESS: "ADD_NEW_ADDRESS_BY_CUSTOMER_SUCCESS",

  UPDATE_ADDRESSES_BY_COSTOMER: "UPDATE_ADDRESSES_BY_COSTOMER",
  UPDATE_ADDRESSES_BY_COSTOMER_FAIL: "UPDATE_ADDRESSES_BY_COSTOMER_FAIL",
  UPDATE_ADDRESSES_BY_COSTOMER_SUCCESS: "UPDATE_ADDRESSES_BY_COSTOMER_SUCCESS",

  REMOVE_ADDRESS_BY_CONSUMER: "REMOVE_ADDRESS_BY_CONSUMER",
  REMOVE_ADDRESS_BY_CONSUMER_FAIL: "REMOVE_ADDRESS_BY_CONSUMER_FAIL",
  REMOVE_ADDRESS_BY_CONSUMER_SUCCESS: "REMOVE_ADDRESS_BY_CONSUMER_SUCCESS",

  SET_SELECT_ADDRESS: "SET_SELECT_ADDRESS",
  SET_SHOW_CUSTOMER_ADDRESSES_MODAL: "SET_SHOW_CUSTOMER_ADDRESSES_MODAL",
  SET_SHOW_DELETE_ADDRESS_MODAL: "SET_SHOW_DELETE_ADDRESS_MODAL",
  SET_SHOW_ADD_UPDATE_ADDRESS_MODAL: "SET_SHOW_ADD_UPDATE_ADDRESS_MODAL",
  SET_SHOW_ADDRESS_ACTIONS_MODAL: "SET_SHOW_ADDRESS_ACTIONS_MODAL",
  SET_SHOW_SEARCH_ADDRESS_MODAL: "SET_SHOW_SEARCH_ADDRESS_MODAL",

  GET_USER_ADDRESS_FROM_LOCATION_SUCCESS:
    "GET_USER_ADDRESS_FROM_LOCATION_SUCCESS",
  GET_USER_ADDRESS_FROM_LOCATION_FAIL: "GET_USER_ADDRESS_FROM_LOCATION_FAIL",

  SEARCH_ADDRESS: "SEARCH_ADDRESS",
  SEARCH_ADDRESS_SUCCESS: "SEARCH_ADDRESS_SUCCESS",
  SEARCH_ADDRESS_FAIL: "SEARCH_ADDRESS_FAIL",

  GET_DISTANCE_BETWEEN_CUSTOMER_AND_VENUE:
    "GET_DISTANCE_BETWEEN_CUSTOMER_AND_VENUE",
  GET_DISTANCE_BETWEEN_CUSTOMER_AND_VENUE_SUCCESS:
    "GET_DISTANCE_BETWEEN_CUSTOMER_AND_VENUE_SUCCESS",
  GET_DISTANCE_BETWEEN_CUSTOMER_AND_VENUE_FAIL:
    "GET_DISTANCE_BETWEEN_CUSTOMER_AND_VENUE_FAIL",
};
